// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqcikAe3vzjo1g0FMsjXpDc9XrzV-9Kzs',
    appId: '1:614284755947:web:3822e2de0953f163368fae',
    messagingSenderId: '614284755947',
    projectId: 'som7ukrvvpx1vwk6dvlufr0fj581om',
    authDomain: 'som7ukrvvpx1vwk6dvlufr0fj581om.firebaseapp.com',
    // Use canonical bucket host for SDKs
    storageBucket: 'som7ukrvvpx1vwk6dvlufr0fj581om.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNX93-td3bjzAmbzqD0mJ3jcU_-tQFHW0',
    appId: '1:614284755947:android:22f08b06b2fe543d368fae',
    messagingSenderId: '614284755947',
    projectId: 'som7ukrvvpx1vwk6dvlufr0fj581om',
    storageBucket: 'som7ukrvvpx1vwk6dvlufr0fj581om.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_OGo_liLcRRCa_fQ042SGBs_AtOMVsV0',
    appId: '1:614284755947:ios:650a0eb6fb332607368fae',
    messagingSenderId: '614284755947',
    projectId: 'som7ukrvvpx1vwk6dvlufr0fj581om',
    storageBucket: 'som7ukrvvpx1vwk6dvlufr0fj581om.appspot.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
